// <auto-generated />
namespace OnlineShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alltercreateDatemodifiedDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alltercreateDatemodifiedDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201710101628084_allter-createDate-modifiedDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
